config/routes.rb
Rails.application.routes.draw do
  
  resources :workouts do
    resources :excercises
  end
  root "workouts#index"
end

app/models/excercise.rb
class Excercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :excercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/excercises_controller.rb
class ExcercisesController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @excercise = @workout.excercises.create(params[:excercise].permit(:name, :sets, :reps))
    redirect_to workout_path(@workout)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  
  def index
    @workouts = Workout.all.order("created_at DESC")
  end
  
  def show
  end
  
  def new
    @workout = Workout.new
  end
  
  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    @workout.update_attributes(workout_params)
    flash[:success] = "Workout updated"
    redirect_to root_path
  end
  
  def destroy
    @workout.destroy
    redirect_to root_path
  end
  
  private
  
  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end
  
  def set_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excercises_helper.rb
module ExcercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/excercises/_excercise.html.haml
%p= excercise.name
%p= excercise.sets
%p= excercise.reps

app/views/excercises/_form.html.haml
= simple_form_for([@workout, @workout.excercises.build]) do |f|
  = f.input :name, input_html: { class: "form-control" }
  = f.input :sets, input_html: { class: "form-control" }
  = f.input :reps, input_html: { class: "form-control" }
  %br/
  = f.button :submit

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Workout Log Application
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags 
%body
  %nav.navbar.navbar-default
    .container
      .navbar-header
        = link_to "Workout Log", root_path, class: "navbar-brand"
      .nav.navbar-nav.navbar-right
        = link_to "New Workout", new_workout_path, class: "navbar navbar-link"
  .container
    = yield

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f|
  = f.input :date, label: "Date"
  = f.input :workout, label: "What area did you workout?", input_html: { class: "form-control" }
  = f.input :mood, label: "How were you feeling?", input_html: { class: "form-control" }
  = f.input :length, label: "How long was the workout?", input_html: { class: "form-control" }
  %br/
  = f.button :submit, input_html: { class: "btn btn-default" }

app/views/workouts/edit.html.haml
%h1 Edit workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/index.html.haml
#index_workouts
  - @workouts.each do |workout|
    %h2= link_to workout.date.strftime("%A, %B %d"), workout
    %h3
      %span Workout:
      = workout.workout

app/views/workouts/new.html.haml
%h1 New workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/show.html.haml
#workout
  %p= @workout.date
  %p= @workout.workout
  %p= @workout.mood
  %p= @workout.length
  
#excercises
  %h2 Excercises
  = render @workout.excercises
  
  %h3 Add an excercise
  = render "excercises/form"
  
= link_to "Back", root_path
= link_to "Edit", edit_workout_path(@workout)
= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?"} 